call npm install --save-dev browser-sync
call npm install --save-dev gulp
call npm install --save-dev gulp-autoprefixer
call npm install --save-dev gulp-cssnano
call npm install --save-dev gulp-sourcemaps
call npm install --save-dev gulp-header
call npm install --save-dev gulp-uglify
call npm install --save-dev gulp-jshint
call npm install --save-dev gulp-rename
call npm install --save-dev gulp-sass
call npm install --save-dev jshint